/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface UiExample {}
}

declare global {


  interface HTMLUiExampleElement extends Components.UiExample, HTMLStencilElement {}
  var HTMLUiExampleElement: {
    prototype: HTMLUiExampleElement;
    new (): HTMLUiExampleElement;
  };
  interface HTMLElementTagNameMap {
    'ui-example': HTMLUiExampleElement;
  }
}

declare namespace LocalJSX {
  interface UiExample {}

  interface IntrinsicElements {
    'ui-example': UiExample;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'ui-example': LocalJSX.UiExample & JSXBase.HTMLAttributes<HTMLUiExampleElement>;
    }
  }
}


